### ISSUE TITLE
Tell us a little more about this repository

### ISSUE THREAD

**Issue by aegershman** [EngineerBetter/scf-pipelines#1]
Apologies for the pushiness, I know this project is only a few hours old. It showed up in my GitHub feed, and now I'm curious what this repository is going to be for:

- Is this related to concourse-up?
- Is this perhaps ci/cd for testing automation for a helm deployment of concourse sourced on top of EKS?

Thanks for your time!

**Comment by DanielJonesEB** [comment]
Hi @aegershman! Good guesses, but not quite right :)

This is for the deployment of SUSE Cloud Foundry on EKS, AKS and GCP. If I get around to finishing it. I hope that's not a disappointment!

I'm guessing you'd be interested in Concourse on Kubernetes? We'd be keen to hear use cases.

**Comment by aegershman** [comment]
Gotcha-- this showed up in my GitHub feed so I figured I'd snoop a bit. To be entirely honest, I was just curious. For the time being I'm perfectly content with and prefer BOSH-deployed Concourse for production workloads. 

Granted, Concourse on Kubernetes could be interesting for...

1. Provisioning speeds?
2. Possibly cheaper?
3. A way to spin up network-isolated CI/CD for other infrastructure provisioning (but you'd need the cluster first, so it's not that different than just using a bosh director)?
4. How interesting would it be if Concourse on Kubernetes could be paired with [something like `kibosh`](https://github.com/cf-platform-eng/kibosh) to get _on-demand Concourse environments_ provisioned as Cloud Foundry service instances? That would be bonkers (and full of operationally complex nightmares).

... But as far as legitimate "I would definitely use that if it were available" use-cases? At least for the time being, I don't really have any.

Thanks for your time answering && making this OSS to learn from, I appreciate it 👍

**Comment by DanielJonesEB** [comment]
Hey @aegershman! Thanks for following up.

> Possibly cheaper?

Probably not if you have a dedicated Kubernetes cluster for Concourse, and given that Kubernetes isn't really hard-multi-tenant, you probably _should_ have a dedicated cluster. The route to cheaper Concourse is to make it securely multi-tenant, and whilst we've got some ideas on how to do that we haven't had the time to look into it.

> How interesting would it be if Concourse on Kubernetes could be paired with something like kibosh to get on-demand Concourse environments provisioned as Cloud Foundry service instances? That would be bonkers (and full of operationally complex nightmares).

The Concourse team, Google and EngineerBetter have all looked into something similar, albeit provisioned via BOSH rather than Kubernetes. Our Airplane.ci system was Concourse-as-a-Service that effectively worked like a service broker with a web UI, and deployed a dedicated Concourse using BOSH. We've moved an internal prototype forwards that could be self-hosted, but again, unless we get a customer interested in sponsoring the development of it, it'll have to wait until we at least get Concourse-Up onto all of AWS, GCP and Azure.
